/*
 * Button.c
 *
 *  Created on: Sep 6, 2018
 *      Author: Phong
 */

#include "Button.h"

extern void Button_Init(void)
{
    PORT_BUTTON_SEL &=~ (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);
    PORT_BUTTON_SEL2 &=~ (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);
    PORT_BUTTON_DIR &=~ (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);
    PORT_BUTTON_REN |= (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);
    PORT_BUTTON_OUT |= (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);


    PORT_BUTTON_IE |= (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);
    PORT_BUTTON_IES |= (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE); //NGAT CANH XUONG
    PORT_BUTTON_IFG &=~ (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);

    __bis_SR_register(GIE);
}

#pragma vector = PORT1_VECTOR
__interrupt void Button_Interrupt(void)
{
    if(PORT_BUTTON_IFG&PIN_BUTTON_MODE)
    {
        _delay_cycles(30000*Freq_MHz);
        if(!(PORT_BUTTON_IN&PIN_BUTTON_MODE))
        {
            P1OUT ^= (BIT0+BIT6);
        }
    }
    PORT_BUTTON_IFG &=~ (PIN_BUTTON_DEC+PIN_BUTTON_INC+PIN_BUTTON_MODE);
}


